apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-store-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/data_scripts"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-store-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi