apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-php-deployment
  name: nginx-php-svc
  namespace: default
spec:
  ports:
  - nodePort: 30600
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-php-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
