apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-deployment
  name: mysql-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: mysql-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql-deployment
    spec:
      containers:
      - image: {{.Values.image.repositorythree}}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        resources: 
          limits:
            cpu: {{.Values.resources.limits.cpu}}
          requests:
            cpu: {{.Values.resources.requests.cpu}}
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
          
        
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-deployment
  name: mysql-svc
  namespace: default
spec:
  ports:
  - port: {{.Values.service2.port}}
    protocol: TCP
    targetPort: {{.Values.service2.port}}
  selector:
    app: mysql-deployment
  sessionAffinity: None
  type: {{.Values.service2.type}}
status:
  loadBalancer: {}
