apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-php-deployment
spec:
  maxReplicas: {{.Values.autoscaling.maxReplicas}}
  minReplicas: {{.Values.autoscaling.minReplicas}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-php-deployment
  targetCPUUtilizationPercentage: {{.Values.autoscaling.targetCPUUtilizationPercentage}}
status:
  currentReplicas: 0
  desiredReplicas: 0
